# Placeholder config for a benchmark

# AgentBuilder Configurations
agentbuilder_class: ...
agentbuilder_config:
  ...

# Translator Configurations
translator_class: ...
translator_config:
  ...

# Dataset loader function
datasetloader_callable: ...
datasetloader_kwargs:
  ...

# Evaluator function
evaluator_callable: ...
evaulator_kwargs:
  ...
