# Placeholder config for a benchmark

# AgentBuilder Configurations
agentbuilder_class: null
agentbuilder_config:
  {}

# Translator Configurations
translator_class: null
translator_config:
  {}

# Dataset loader function
datasetloader_callable: null
datasetloader_kwargs:
  {}

# Evaluator function
evaluator_callable: null
evaulator_kwargs:
  {}
# Evaluation result saver function
evaluationresultsaver_callable: null
evaluationresultsaver_kwargs:
  {}
