benchmark_name: &benchmark_name "Tool Call Benchmark"

agentbuilder_class: core.agentbuilder.LangGraphAgentBuilder
agentbuilder_config:
  model_name: &model_name gemini-2.5-pro
  model_class: langchain_google_genai.ChatGoogleGenerativeAI
  tools: benchmark.tool_call.tools.tools
  system_prompt_path: benchmark/tool_call/system_prompt.txt

translator_class: benchmark.tool_call.utils.ToolCallBenchmarkTranslator
translator_config: {}

datasetloader_class: benchmark.tool_call.utils.ToolCallBenchmarkDatasetLoader
datasetloader_config:
  path: benchmark/tool_call/dataset.json

agentrunner_class: core.agentrunner.SyncThreadPoolAgentRunner
agentrunner_config:
  thread_count: 5

evaluator_class: benchmark.tool_call.utils.ToolCallBenchmarkEvaluator
evaluator_config: {}

evaluationsaver_class: core.evaluationsaver.DashboardEvaluationSaver
evaluationsaver_config:
  benchmark_name: *benchmark_name
  run_id: *model_name
  output_dir: "evaluations"
