agentbuilder_class: core.agentbuilder.LangGraphAgentBuilder
agentbuilder_config:
  model: gemini-2.5-pro
  tools: benchmark.tool_call.tools.tools
  system_prompt_path: benchmark/tool_call/system_prompt.txt

translator_class: core.translator.LangGraphTranslator
translator_config: {}

datasetloader_class: benchmark.tool_call.utils.ToolCallBenchmarkDatasetLoader
datasetloader_config:
  path: benchmark/tool_call/dataset_expressions.json

evaluator_class: benchmark.tool_call.utils.ToolCallBenchmarkEvaluator
evaluator_config: {}

evaluationsaver_class: benchmark.tool_call.utils.ToolCallBenchmarkEvaluationSaver
evaluationsaver_config: {}
