agentbuilder_class: core.agentbuilder.LangGraphAgentBuilder
agentbuilder_config:
  model_name: llama3.1:8b
  model_class: langchain_ollama.ChatOllama
  tools: benchmark.tool_call.tools.tools
  system_prompt_path: benchmark/tool_call/system_prompt.txt

translator_class: core.translator.LangGraphTranslator
translator_config: {}

datasetloader_class: benchmark.tool_call.utils.ToolCallBenchmarkDatasetLoader
datasetloader_config:
  path: benchmark/tool_call/dataset_expressions.json

agentrunner_class: core.agentrunner.SyncThreadPoolAgentRunner
agentrunner_config:
  thread_count: 1

evaluator_class: benchmark.tool_call.utils.ToolCallBenchmarkEvaluator
evaluator_config: {}

evaluationsaver_class: benchmark.tool_call.utils.ToolCallBenchmarkEvaluationSaver
evaluationsaver_config:
  output_path: evaluation.dict
